mqtt:
  brocker: 127.0.0.1
  topic: smarthouse
  ha_topic: homeassistant

common:
  name: Inputs_dbus
  model: DBus Sensors
  model_name: DBus Sensors
  manufacturer: Weekend
  sw_version: 0.0.3

sensors:
#  164: 'Этаж 1, Спальня, выкл на входе N 1'
#  168: 'Этаж 1, Спальня, выкл на входе N 2'
#  167: 'Этаж 1, Спальня, выкл по центру комнаты'
#  173: 'Этаж 1, Ванная, выкл на входе'
#  185: 'Этаж 1, Ванная, выкл в постирочной'
#  172: 'Этаж 1, Холл, выкл между спальней и кухней'
#  180: 'Этаж 1, Холл, выкл на входе из гаража'
#  171: 'Этаж 1, Кабинет Оли, вход'
  184: 'Этаж 1, Кабинет Гриши, вход'
#  161: 'Этаж 1, туалет'
#  163: 'Этаж 2, Оражерея, основной'
#  189: 'Этаж 2, Оранжерея, доп'
#  160: 'Этаж 2, вверху лестницы'
#  175: 'Этаж 2, внизу лестницы'
#  181: 'Этаж 2, Гардероб'
#  191: 'Этаж 2, Спальня Лёвы'
#  165: 'Этаж 2, Гостевая'
  188: 'Тестовый выключатель'
