mqtt:
  brocker: 127.0.0.1
  topic: smarthouse
  ha_topic: homeassistant

common:
  name: Lamp_dbus
  model: DBus Relays
  model_name: DBus Relays
  manufacturer: Weekend
  sw_version: 0.0.3

switches:
  42: 'Кабинет Гриши'
  34: 'Кабинет Оли'
  35: 'Холл'
  53: 'Туалет'
  46: 'Туалет, вентилятор'
  47: 'Ванная, основной свет'
  38: 'Ванная, свет в постирочной'
  54: 'Спальня, основной свет'
  52: 'Спальня, ночник'
  51: 'Вход, дверь'
  32: 'Вход, крыльцо, улица'
  55: 'Этаж 2, свет'
#  40, ' New 1'
#  62, 'Освещение на улице'
#  61, 'Розетка роутер'

#    switch_01: {hw_num:  1, description: "Реле в кабинете"}
